[2015-06-16 05:17:27] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:17:33] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:30:30] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:31:05] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:31:13] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:31:30] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:31:34] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:31:39] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:31:47] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:32:03] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:32:07] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:33:35] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:34:02] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:34:03] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:34:09] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:34:15] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:34:18] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 05:45:26] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:45:27] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:45:31] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:45:34] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:45:41] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:45:44] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:45:51] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:48:05] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:50:14] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:51:51] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:51:55] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:52:07] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:54:37] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:54:57] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:55:59] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:56:09] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:56:14] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:56:24] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:56:44] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:57:08] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:59:39] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:59:42] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 05:59:53] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:02:40] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:02:41] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:02:51] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:02:52] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:02:55] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:04:35] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function abort()' in /var/www/html/testing/app/routes.php:18
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:04:49] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:05:27] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:05:52] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:05:54] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:05:54] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:06:06] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:06:09] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:06:24] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:07:34] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:07:53] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')'' in /var/www/html/testing/app/routes.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:08:01] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:08:17] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:08:21] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:10:48] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:10:58] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:13:17] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'function' (T_FUNCTION)' in /var/www/html/testing/app/routes.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:13:33] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'function' (T_FUNCTION)' in /var/www/html/testing/app/routes.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:18:23] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:19:52] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:21:12] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:22:30] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:22:32] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 06:23:55] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Url' not found' in /var/www/html/testing/app/controllers/UrlController.php:36
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:24:57] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Url' not found' in /var/www/html/testing/app/controllers/UrlController.php:36
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:25:31] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Url' not found' in /var/www/html/testing/app/controllers/UrlController.php:36
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:26:58] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::save()' in /var/www/html/testing/app/controllers/UrlController.php:44
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:27:47] production.ERROR: exception 'ErrorException' with message 'Undefined variable: urls' in /var/www/html/testing/app/controllers/UrlController.php:48
Stack trace:
#0 /var/www/html/testing/app/controllers/UrlController.php(48): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/html/t...', 48, Array)
#1 [internal function]: UrlController->store()
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#4 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#5 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#18 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#19 {main} [] []
[2015-06-16 06:28:22] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::save()' in /var/www/html/testing/app/controllers/UrlController.php:44
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:30:37] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::toArray()' in /var/www/html/testing/app/controllers/UrlController.php:48
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:30:55] production.ERROR: exception 'ErrorException' with message 'Undefined variable: urls' in /var/www/html/testing/app/controllers/UrlController.php:48
Stack trace:
#0 /var/www/html/testing/app/controllers/UrlController.php(48): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/html/t...', 48, Array)
#1 [internal function]: UrlController->store()
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#4 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#5 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#18 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#19 {main} [] []
[2015-06-16 06:31:16] production.ERROR: exception 'ErrorException' with message 'Undefined variable: urls' in /var/www/html/testing/app/controllers/UrlController.php:48
Stack trace:
#0 /var/www/html/testing/app/controllers/UrlController.php(48): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/html/t...', 48, Array)
#1 [internal function]: UrlController->store()
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#4 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#5 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#18 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#19 {main} [] []
[2015-06-16 06:35:53] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::save()' in /var/www/html/testing/app/controllers/UrlController.php:44
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:37:46] production.ERROR: exception 'ErrorException' with message 'Undefined property: Illuminate\Support\Facades\URL::$user' in /var/www/html/testing/app/controllers/UrlController.php:44
Stack trace:
#0 /var/www/html/testing/app/controllers/UrlController.php(44): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', '/var/www/html/t...', 44, Array)
#1 [internal function]: UrlController->store()
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#4 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#5 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#18 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#19 {main} [] []
[2015-06-16 06:39:12] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::toArray()' in /var/www/html/testing/app/controllers/UrlController.php:48
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:39:29] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' in /var/www/html/testing/app/controllers/UrlController.php:43
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:39:47] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::save()' in /var/www/html/testing/app/controllers/UrlController.php:43
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:40:19] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::save()' in /var/www/html/testing/app/controllers/UrlController.php:43
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:43:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::save()' in /var/www/html/testing/app/controllers/UrlController.php:43
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:48:39] production.ERROR: exception 'ErrorException' with message 'Object of class Illuminate\Support\Facades\URL could not be converted to string' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Support/helpers.php:900
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(4096, 'Object of class...', '/var/www/html/t...', 900, Array)
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Support/helpers.php(900): preg_replace('/\?/', 'Object', 'insert into `us...', 1)
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/QueryException.php(55): str_replace_array('\?', Array, 'insert into `us...')
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/QueryException.php(37): Illuminate\Database\QueryException->formatMessage('insert into `us...', Array, Object(PDOException))
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(627): Illuminate\Database\QueryException->__construct('insert into `us...', Array, Object(PDOException))
#5 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#7 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `us...', Array)
#8 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `us...', Array)
#9 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `us...', Array, 'id')
#10 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#11 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#12 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#13 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#14 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#15 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#16 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#17 [internal function]: UrlController->store()
#18 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#19 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#20 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#21 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#22 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#23 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#24 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#28 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#30 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#31 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#32 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#33 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#34 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#35 {main} [] []
[2015-06-16 06:49:14] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function save() on a non-object' in /var/www/html/testing/app/controllers/UrlController.php:45
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:49:28] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'users_username_unique'' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDOStatement->execute(Array)
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `us...', Array)
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `us...', Array)
#5 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `us...', Array)
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `us...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#14 [internal function]: UrlController->store()
#15 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#16 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#17 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#18 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#21 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#30 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#31 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'users_username_unique' (SQL: insert into `users` (`updated_at`, `created_at`) values (2015-06-16 06:49:28, 2015-06-16 06:49:28))' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `us...', Array)
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `us...', Array)
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `us...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UrlController->store()
#13 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#15 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#16 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#19 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#29 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#30 {main} [] []
[2015-06-16 06:52:49] production.ERROR: exception 'ErrorException' with message 'Creating default object from empty value' in /var/www/html/testing/app/controllers/UrlController.php:37
Stack trace:
#0 /var/www/html/testing/app/controllers/UrlController.php(37): Illuminate\Exception\Handler->handleError(2, 'Creating defaul...', '/var/www/html/t...', 37, Array)
#1 [internal function]: UrlController->store()
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#4 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#5 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#18 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#19 {main} [] []
[2015-06-16 06:53:17] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::save()' in /var/www/html/testing/app/controllers/UrlController.php:45
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:54:27] production.ERROR: exception 'ErrorException' with message 'Undefined variable: URL' in /var/www/html/testing/app/controllers/UrlController.php:45
Stack trace:
#0 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/html/t...', 45, Array)
#1 [internal function]: UrlController->store()
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#4 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#5 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#18 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#19 {main} [] []
[2015-06-16 06:56:13] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Url' not found' in /var/www/html/testing/app/controllers/UrlController.php:36
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:57:25] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';', expecting identifier (T_STRING)' in /var/www/html/testing/app/controllers/UrlController.php:2
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:58:07] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'main(): Failed opening required '../models/Url.php' (include_path='/var/www/html/testing/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear')' in /var/www/html/testing/app/controllers/UrlController.php:2
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:58:40] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'main(): Failed opening required '../../models/Url.php' (include_path='/var/www/html/testing/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear')' in /var/www/html/testing/app/controllers/UrlController.php:2
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 06:58:54] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'main(): Failed opening required '/models/Url.php' (include_path='/var/www/html/testing/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear')' in /var/www/html/testing/app/controllers/UrlController.php:2
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 08:40:41] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Urls' not found' in /var/www/html/testing/app/controllers/UrlController.php:36
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 08:42:39] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Support\Facades\URL::save()' in /var/www/html/testing/app/controllers/UrlController.php:45
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 08:57:28] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Url' not found' in /var/www/html/testing/app/controllers/UrlController.php:36
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 08:59:49] production.ERROR: exception 'ErrorException' with message 'include(/var/www/html/testing/app/models/Url.php): failed to open stream: No such file or directory' in /var/www/html/testing/vendor/composer/ClassLoader.php:412
Stack trace:
#0 /var/www/html/testing/vendor/composer/ClassLoader.php(412): Illuminate\Exception\Handler->handleError(2, 'include(/var/ww...', '/var/www/html/t...', 412, Array)
#1 /var/www/html/testing/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /var/www/html/testing/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/html/t...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Url')
#4 /var/www/html/testing/app/controllers/UrlController.php(36): spl_autoload_call('Url')
#5 [internal function]: UrlController->store()
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#7 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#8 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#9 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#12 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#22 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#23 {main} [] []
[2015-06-16 09:00:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Url' not found' in /var/www/html/testing/app/controllers/UrlController.php:36
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 09:00:37] production.ERROR: exception 'ErrorException' with message 'include(/var/www/html/testing/app/models/Url.php): failed to open stream: No such file or directory' in /var/www/html/testing/vendor/composer/ClassLoader.php:412
Stack trace:
#0 /var/www/html/testing/vendor/composer/ClassLoader.php(412): Illuminate\Exception\Handler->handleError(2, 'include(/var/ww...', '/var/www/html/t...', 412, Array)
#1 /var/www/html/testing/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /var/www/html/testing/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/html/t...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Url')
#4 /var/www/html/testing/app/controllers/UrlController.php(36): spl_autoload_call('Url')
#5 [internal function]: UrlController->store()
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#7 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#8 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#9 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#12 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#22 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#23 {main} [] []
[2015-06-16 09:01:54] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 09:02:00] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/testing/bootstrap/compiled.php:5751
Stack trace:
#0 /var/www/html/testing/bootstrap/compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/testing/bootstrap/compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#11 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#12 {main} [] []
[2015-06-16 09:02:23] production.ERROR: exception 'ErrorException' with message 'include(/var/www/html/testing/app/models/Url.php): failed to open stream: No such file or directory' in /var/www/html/testing/vendor/composer/ClassLoader.php:412
Stack trace:
#0 /var/www/html/testing/vendor/composer/ClassLoader.php(412): Illuminate\Exception\Handler->handleError(2, 'include(/var/ww...', '/var/www/html/t...', 412, Array)
#1 /var/www/html/testing/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /var/www/html/testing/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/html/t...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Url')
#4 /var/www/html/testing/app/controllers/UrlController.php(36): spl_autoload_call('Url')
#5 [internal function]: UrlController->store()
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#7 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#8 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#9 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#12 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#22 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#23 {main} [] []
[2015-06-16 09:02:53] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDOStatement->execute(Array)
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ur...', Array)
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#5 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#14 [internal function]: UrlController->store()
#15 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#16 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#17 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#18 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#21 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#30 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#31 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null (SQL: insert into `urls` (`url`, `description`, `user_id`, `updated_at`, `created_at`) values (, , 1, 2015-06-16 09:02:53, 2015-06-16 09:02:53))' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UrlController->store()
#13 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#15 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#16 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#19 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#29 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#30 {main} [] []
[2015-06-16 09:03:56] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDOStatement->execute(Array)
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ur...', Array)
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#5 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#14 [internal function]: UrlController->store()
#15 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#16 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#17 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#18 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#21 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#30 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#31 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null (SQL: insert into `urls` (`url`, `description`, `user_id`, `updated_at`, `created_at`) values (, , 1, 2015-06-16 09:03:56, 2015-06-16 09:03:56))' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UrlController->store()
#13 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#15 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#16 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#19 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#29 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#30 {main} [] []
[2015-06-16 09:04:27] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDOStatement->execute(Array)
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ur...', Array)
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#5 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#14 [internal function]: UrlController->store()
#15 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#16 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#17 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#18 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#21 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#30 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#31 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null (SQL: insert into `urls` (`url`, `description`, `user_id`, `updated_at`, `created_at`) values (, , 1, 2015-06-16 09:04:27, 2015-06-16 09:04:27))' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UrlController->store()
#13 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#15 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#16 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#19 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#29 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#30 {main} [] []
[2015-06-16 09:04:58] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDOStatement->execute(Array)
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ur...', Array)
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#5 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#14 [internal function]: UrlController->store()
#15 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#16 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#17 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#18 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#21 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#30 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#31 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null (SQL: insert into `urls` (`url`, `description`, `user_id`, `updated_at`, `created_at`) values (, , 1, 2015-06-16 09:04:58, 2015-06-16 09:04:58))' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UrlController->store()
#13 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#15 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#16 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#19 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#29 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#30 {main} [] []
[2015-06-16 09:05:16] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'description' cannot be null' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDOStatement->execute(Array)
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ur...', Array)
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#5 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#14 [internal function]: UrlController->store()
#15 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#16 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#17 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#18 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#21 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#30 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#31 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'description' cannot be null (SQL: insert into `urls` (`url`, `description`, `user_id`, `updated_at`, `created_at`) values (google.com, , 1, 2015-06-16 09:05:16, 2015-06-16 09:05:16))' in /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ur...', Array, Object(Closure))
#1 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ur...', Array, Object(Closure))
#2 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ur...', Array)
#3 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ur...', Array)
#4 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ur...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/testing/bootstrap/compiled.php(6913): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/testing/bootstrap/compiled.php(6903): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/testing/bootstrap/compiled.php(6860): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/testing/app/controllers/UrlController.php(45): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UrlController->store()
#13 /var/www/html/testing/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/html/testing/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array)
#15 /var/www/html/testing/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(UrlController), Object(Illuminate\Routing\Route), 'store')
#16 /var/www/html/testing/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UrlController', 'store')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/html/testing/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#19 /var/www/html/testing/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/html/testing/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/html/testing/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/testing/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/testing/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/testing/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/testing/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/testing/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/testing/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /var/www/html/testing/public/index.php(49): Illuminate\Foundation\Application->run()
#29 /var/www/html/testing/server.php(19): require_once('/var/www/html/t...')
#30 {main} [] []
[2015-06-16 09:11:50] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}', expecting ')'' in /var/www/html/testing/app/controllers/UrlController.php:92
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-06-16 09:11:59] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/html/testing/app/controllers/UrlController.php:91
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
